schema_version = "1.0.0"

id = "blendmsh"
version = "1.1.0"
name = "Blendmsh"
tagline = "Blendmsh is a bridge between Blender and Gmsh, a 3D finite element mesh generator"
maintainer = "Senthur Raj"
type = "add-on"
blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

[permissions]
files = "Save mesh files to disk"
