schema_version = "1.0.0"

id = "blendmsh"
version = "1.1.0"
name = "Blendmsh"
tagline = "Blendmsh bridges Blender and Gmsh for 3D finite element meshing"
maintainer = "Senthur Raj"
type = "add-on"
blender_version_min = "4.2.0"

wheels = [
    "./wheels/gmsh-4.13.1-py2.py3-none-win_amd64.whl",
    "./wheels/markdown_it_py-3.0.0-py3-none-any.whl",
    "./wheels/mdurl-0.1.2-py3-none-any.whl",
    "./wheels/meshio-5.3.5-py3-none-any.whl",
    "./wheels/numpy-2.1.2-cp311-cp311-win_amd64.whl",
    "./wheels/pygments-2.18.0-py3-none-any.whl",
    "./wheels/pygmsh-7.1.17-py3-none-any.whl",
    "./wheels/rich-13.9.3-py3-none-any.whl",
]

license = [
  "SPDX:GPL-3.0-or-later",
]

[permissions]
files = "Save mesh files to disk"
